#!/bin/sh

## hyphop ##

for i in MX3_open_back.JPG  MX3_open_top.JPG; do

    s=${i%.JPG}.small.jpg

#    convert $i -resize 1920 -quality 75 $s

done

## byby exif meta ;)

for i in *.jpg ; do
    exiftool -overwrite_original -*= $i
done